<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Generador de Dietas Saludables</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f8f0;
        }
        
        header {
            background-color: #4CAF50;
            color: white;
            text-align: center;
            padding: 2rem;
        }
        
        nav {
            background-color: #388E3C;
            padding: 1rem;
            display: flex;
            justify-content: center;
            gap: 2rem;
        }
        
        nav a {
            color: white;
            text-decoration: none;
            padding: 0.5rem 1rem;
            border-radius: 4px;
            transition: background-color 0.3s;
        }
        
        nav a:hover {
            background-color: #2E7D32;
        }
        
        main {
            max-width: 800px;
            margin: 2rem auto;
            padding: 0 1rem;
        }
        
        .section {
            background-color: white;
            border-radius: 8px;
            padding: 2rem;
            margin-bottom: 2rem;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        
        .form-group {
            margin-bottom: 1rem;
        }
        
        label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: bold;
        }
        
        input, select {
            width: 100%;
            padding: 0.5rem;
            border: 1px solid #ddd;
            border-radius: 4px;
            margin-bottom: 1rem;
        }
        
        button {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 0.75rem 1.5rem;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1rem;
        }
        
        button:hover {
            background-color: #388E3C;
        }
        
        .habit-card {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 1rem;
            margin-bottom: 1rem;
            background-color: #fff;
        }
        
        .meal-plan {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 1rem;
            margin-top: 1rem;
        }
        
        .meal-day {
            margin-bottom: 1rem;
        }

        footer {
            background-color: #388E3C;
            color: white;
            padding: 2rem;
            margin-top: 2rem;
            text-align: center;
        }
        
        .contact-section {
            max-width: 800px;
            margin: 0 auto;
        }
        
        .social-links {
            display: flex;
            justify-content: center;
            gap: 2rem;
            margin: 1rem 0;
        }
        
        .social-links a {
            color: white;
            text-decoration: none;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }
        
        .social-links a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <header>
        <h1>💪 Vida Saludable</h1>
        <p>Genera tu plan de alimentación personalizado y aprende buenos hábitos</p>
    </header>
    
    <nav>
        <a href="#generator">Generador de Dietas</a>
        <a href="#habits">Buenos Hábitos</a>
        <a href="#tips">Consejos</a>
    </nav>
    
    <main>
        <section id="generator" class="section">
            <h2>Generador de Dietas Saludables</h2>
            <div class="form-group">
                <label for="age">Edad:</label>
                <input type="number" id="age" min="1" max="120">
                
                <label for="weight">Peso (kg):</label>
                <input type="number" id="weight" min="1" max="300">
                
                <label for="height">Altura (cm):</label>
                <input type="number" id="height" min="1" max="300">
                
                <label for="activity">Nivel de Actividad:</label>
                <select id="activity">
                    <option value="sedentary">Sedentario</option>
                    <option value="light">Actividad Ligera</option>
                    <option value="moderate">Actividad Moderada</option>
                    <option value="high">Actividad Intensa</option>
                </select>
                
                <label for="goal">Objetivo:</label>
                <select id="goal">
                    <option value="maintain">Mantener Peso</option>
                    <option value="lose">Perder Peso</option>
                    <option value="gain">Ganar Peso</option>
                </select>
                
                <button onclick="generateDiet()">Generar Plan de Alimentación</button>
            </div>
            
            <div id="diet-result" class="meal-plan"></div>
        </section>
        
        <section id="habits" class="section">
            <h2>Buenos Hábitos Diarios</h2>
            <div class="habit-card">
                <h3>🌅 Rutina Matutina</h3>
                <ul>
                    <li>Despertar temprano (6:00 - 7:00 AM)</li>
                    <li>Beber un vaso de agua al despertar</li>
                    <li>15 minutos de ejercicios de estiramiento</li>
                    <li>Desayuno equilibrado</li>
                </ul>
            </div>
            
            <div class="habit-card">
                <h3>💪 Actividad Física</h3>
                <ul>
                    <li>30 minutos de ejercicio diario</li>
                    <li>Caminar 10,000 pasos</li>
                    <li>Tomar descansos activos cada 2 horas</li>
                </ul>
            </div>
            
            <div class="habit-card">
                <h3>🥗 Alimentación</h3>
                <ul>
                    <li>5 porciones de frutas y verduras al día</li>
                    <li>Beber 2 litros de agua</li>
                    <li>Evitar alimentos procesados</li>
                    <li>Comer despacio y sin distracciones</li>
                </ul>
            </div>
        </section>
        
        <section id="tips" class="section">
            <h2>Consejos para una Vida Saludable</h2>
            <div class="habit-card">
                <h3>🧘‍♀️ Salud Mental</h3>
                <ul>
                    <li>Practica meditación 10 minutos al día</li>
                    <li>Mantén un diario de gratitud</li>
                    <li>Establece límites saludables</li>
                    <li>Dedica tiempo a tus hobbies</li>
                </ul>
            </div>
            
            <div class="habit-card">
                <h3>😴 Descanso</h3>
                <ul>
                    <li>Duerme 7-8 horas por noche</li>
                    <li>Mantén un horario regular de sueño</li>
                    <li>Evita pantallas 1 hora antes de dormir</li>
                    <li>Crea un ambiente relajante para dormir</li>
                </ul>
            </div>
        </section>
    </main>

    <footer>
        <div class="contact-section">
            <h2>Contáctanos</h2>
            <p>¿Tienes preguntas sobre tu plan de alimentación o necesitas asesoría personalizada?</p>
            
            <div class="social-links">
                <a href="https://www.instagram.com/vidasaludable.pe" target="_blank">
                    📸 @vidasaludable.pe
                </a>
                <a href="https://www.facebook.com/vidasaludableperu" target="_blank">
                    👥 Vida Saludable Perú
                </a>
            </div>
            
            <p>📞 Teléfono: 601 262531</p>
            <p>Horario de atención: Lunes a Viernes 9:00 AM - 6:00 PM</p>
        </div>
    </footer>

    <script>
        function generateDiet() {
            const age = document.getElementById('age').value;
            const weight = document.getElementById('weight').value;
            const height = document.getElementById('height').value;
            const activity = document.getElementById('activity').value;
            const goal = document.getElementById('goal').value;
            
            if (!age || !weight || !height) {
                alert('Por favor, completa todos los campos');
                return;
            }
            
            const mealPlan = {
                desayuno: [
                    "Avena con frutas y nueces",
                    "Yogur con granola y miel",
                    "Tostadas integrales con aguacate",
                    "Batido de proteínas con plátano",
                    "Huevos revueltos con espinacas"
                ],
                almuerzo: [
                    "Ensalada de quinoa con pollo",
                    "Pescado al horno con verduras",
                    "Wrap de pavo con verduras",
                    "Bowl de arroz integral con legumbres",
                    "Pasta integral con salsa de verduras"
                ],
                cena: [
                    "Sopa de verduras con proteína magra",
                    "Pescado a la plancha con ensalada",
                    "Tofu salteado con verduras",
                    "Pechuga de pollo con vegetales asados",
                    "Ensalada de atún con aguacate"
                ]
            };
            
            let result = '<h3>Tu Plan de Alimentación Personalizado</h3>';
            for (let i = 1; i <= 5; i++) {
                result += `
                    <div class="meal-day">
                        <h4>Día ${i}</h4>
                        <p><strong>Desayuno:</strong> ${mealPlan.desayuno[i-1]}</p>
                        <p><strong>Almuerzo:</strong> ${mealPlan.almuerzo[i-1]}</p>
                        <p><strong>Cena:</strong> ${mealPlan.cena[i-1]}</p>
                        <p><em>Snacks saludables:</em> Frutas, nueces, yogur natural</p>
                    </div>
                `;
            }
            
            document.getElementById('diet-result').innerHTML = result;
        }
    </script>
</body>
</html>
